
name: "CLA Assistant"
on:
  pull_request:
    types: [opened,synchronize,closed]
    
jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@v1 
    - name: "CLA Assistant"
      #if: github.event.action == 'opened' || github.event.action == 'synchronize'
      uses: ibakshay/action-template@dev-release
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }} 
      with: 
        pathToClaSignatures: 'signatures/cla.json'
        pathToCLADocument: 'https://github.com/ibakshay/test-action-workflow/blob/master/cla.md'
        branch: 'master'

